<?php

namespace Database\Seeders;

use App\Models\Product;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class ProductDatabaseSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $items =  [
            ['name' => 'Panadol 500mg giảm đau, hạ sốt (10 vỉ x 12 viên)', 'description' => 'Panadol chứa paracetamol là một chất giảm đau, hạ sốt. Điều trị đau nhẹ đến vừa bao gồm: Đau đầu. Đau nửa đầu. Đau cơ. Đau bụng kinh, Đau họng. Đau cơ xương. Sốt và đau sau khi tiêm vacxin. Đau sau khi nhổ răng hoặc sau các thủ thuật nha khoa. Đau răng. Đau do viêm xương khớp.', 'ingredient' => 'Hoạt chất: Paracetamol 500mg.', 'intruction' => 'Dùng 500mg đến 1g paracetamol (1 - 2 viên/lần), sau mỗi 4 - 6 giờ nếu cần.', 'img' => 'panadol-120v.jpg', 'unit' => 'Hộp', 'brand_id' => '1', 'category_ids' => [1]],
            ['name' => 'Panadol Cảm Cúm giảm các triệu chứng sốt, đau, sung huyết mũi (15 vỉ x 12 viên)', 'description' => 'Panadol Cảm cúm làm giảm các triệu chứng của cảm cúm như sốt, đau và xung huyết mũi.', 'ingredient' => 'Hoạt chất: Paracetamol 500mg, Caffeine 25mg, Phenylephrine hydrochloride 5mg.', 'intruction' => 'Chỉ dùng đường uống.', 'img' => 'panadol-cold-flu.jpg', 'unit' => 'Hộp',  'brand_id' => '2', 'category_ids' => [1]],
            ['name' => 'Viên nhai Panadol Trẻ Em 120mg giảm đau, hạ sốt (8 vỉ x 12 viên)', 'description' => 'Paracetamol là một chất giảm đau, hạ sốt. Đau đầu, đau nửa đầu, đau cơ, đau họng, đau cơ xương, sốt và đau sau khi tiêm vắc xin, đau sau khi nhổ răng hoặc sau các thủ thuật nha khoa, đau răng, đau do viêm xương khớp.', 'ingredient' => 'Hoạt chất: Paracetamol 120 mg/viên.', 'intruction' => 'Liều tối đa hàng ngày: 60 mg/kg cân nặng chia thành nhiều lần, mỗi lần 10 - 15 mg/kg cân nặng dùng trong 24 giờ.', 'img' => 'panadol-children-120mg.jpg', 'unit' => 'Hộp',  'brand_id' => '2', 'category_ids' => [1]],
            ['name' => 'Hapacol Blue 500mg giảm đau, hạ sốt (10 vỉ x 10 viên)', 'description' => 'Hạ sốt ở bệnh nhân bị cảm hay những bệnh có liên quan đến sốt.', 'ingredient' => 'Hoạt chất: Paracetamol 500 mg.', 'intruction' => 'Hoạt chất: Paracetamol 500 mg.', 'img' => 'hapacol-blue-500mg.jpg', 'unit' => 'Hộp',  'brand_id' => '3', 'category_ids' => [1]],
            ['name' => 'Hỗn dịch uống Cratsuca 1g trị viêm loét dạ dày, tá tràng (20 gói x 10ml) Tiêu hóa, gan mật Thuốc trị đau dạ dày', 'description' => 'Sucralfat được chỉ định ở người lớn và trẻ em trên 14 tuổi bị loét tá tràng, loét dạ dày, viêm dạ dày mạn tính, và dự phòng xuất huyết đường tiêu hóa với loét do stress ở bệnh nhân bệnh nặng.', 'ingredient' => 'Hoạt chất: Sucralfat 1 g', 'intruction' => 'Dùng đường uống.', 'img' => 'cratsuca-1g-mac-dinh-2-1.jpg', 'unit' => 'Hộp',  'brand_id' => '1', 'category_ids' => [1, 2]],
            ['name' => 'Hỗn dịch uống Ebysta 20mg trị trào ngược dạ dày, thực quản (20 gói x 10ml)Tiêu hóa, gan mật Thuốc trị đau dạ dày', 'description' => 'Điều trị trào ngược dạ dày thực quản liên quan đến sự trào ngược.', 'ingredient' => 'Thành phần dược chất: Sodium alginate 500mg, Calcium carbonate 160mg, Sodium bicarbonate 267mg.', 'intruction' => 'Uống thuốc sau bữa ăn và trước khi đi ngủ ( tối đa 4 lần/ngày).', 'img' => 'ebysta-h-20g-1-1.jpg', 'unit' => 'Hộp', 'brand_id' => '1', 'category_ids' => [1, 2]],
            ['name' => 'Glotadol 500 hạ sốt, giảm các cơn đau từ nhẹ đến vừa', 'description' => 'Làm giảm các cơn đau từ nhẹ đến vừa như đau đầu và đau cơ thông thường, đau nhức do cảm cúm hay cảm lạnh, đau lưng, đau răng, đau do viêm khớp nhẹ và đau do hành kinh.', 'ingredient' => 'Tá dược: Povidon K30, natri starch glycolat A, natri lauryl sulfat, magnesi stearat, hypromellose 2910, 6cps, macrogol 400, propylen glycol, talc, titan dioxyd.', 'intruction' => 'Người lớn và trẻ em trên 12 tuổi: uống 1 - 2 viên/lần, khoảng cách giữa các lần uống thuốc từ 4 - 6 giờ, không quá 8 viên/ngày.', 'img' => 'glotadol-500mg-h-100v-mac-dinh-2.jpg', 'unit' => 'Hộp',  'brand_id' => '2', 'category_ids' => [1]],
            ['name' => 'Mexcold Plus giảm đau, hạ sốt (10 vỉ x 10 viên)', 'description' => 'Điều trị các triệu chứng đau như: đau đầu, đau răng, đau lưng, đau nhức bắp thịt, đau bụng kinh, đau do thấp khớp, nhức mỏi cơ.', 'ingredient' => 'Thành phần tá dược: Povidon, Natri lauryl sulfat, Cellulose vi tinh thể, Crospovidon, Magnesi stearat, Hydroxypropyl methylcellulose, Talc, Titan dioxyd, Macrogol 6000, sắt oxyd.', 'intruction' => 'Người lớn và trẻ em từ 12 tuổi trở lên: uống 1 - 2 viên x 2 - 3 lần/ngày. Không uống quá 8 viên/ngày.', 'img' => 'mexcold-plus-h-100v-mac-dinh-2.jpg', 'unit' => 'Hộp',  'brand_id' => '2', 'category_ids' => [1]],
            ['name' => 'Hỗn dịch uống Phosphalugel', 'description' => 'Phosphalugel là một thuốc kháng axit. Nó làm giảm độ axit của dạ dày.', 'ingredient' => 'Tá dược: Calcium sulphate dihydrate, pectin, agar 800, hương cam, potassium sorbate, dung dịch sorbitol (không tinh thể), nước tinh khiết vừa đủ để tạo thành gói 20 g.', 'intruction' => 'Liều thông thường 1 đến 2 gói uống 2 đến 3 lần mỗi ngày.', 'img' => 'phosphalugel.jpg', 'unit' => 'Hộp',  'brand_id' => '3', 'category_ids' => [1]],
            ['name' => 'Mexcold Imex 500 giảm đau từ nhẹ đến vừa', 'description' => 'Giảm đau tạm thời trong các trường hợp đau nhẹ và vừa. Thuốc có hiệu quả nhất với cơn đau cường độ thấp, có nguồn gốc không phải nội tạng.', 'ingredient' => 'á dược: Cellulose vi tinh thể, Tinh bột mì, Natri lauryl sulfat, Magnesi stearat.', 'intruction' => 'Hàm lượng paracetamol chứa trong viên nang cứng MEXCOLD IMEX 500 không thích hợp sử dụng cho trẻ em dưới 11 tuổi.', 'img' => 'pms-mexcold-500mg-1.jpg', 'unit' => 'Chai',  'brand_id' => '1', 'category_ids' => [1]],
            ['name' => 'Glotadol Power giảm các cơn đau nặng, hạ sốt', 'description' => 'Thuốc được dùng giảm các cơn đau nặng như đau đầu, đau nửa đầu, đau nhức do cảm lạnh và cảm cúm,', 'ingredient' => 'Hoạt chất: Paracetamol 650 mg, Cafein 65 mg.', 'intruction' => 'Người lớn và trẻ em từ 12 tuổi trở lên: uống 1 viên/lần, khoảng cách giữa các lần uống thuốc từ 4 - 6 giờ, không dùng quá 6 viên trong vòng 24 giờ.', 'img' => 'thuoc-giam-dau-ha-sot-glotadol.jpg', 'unit' => 'Chai',  'brand_id' => '3', 'category_ids' => [1]],
            ['name' => 'SaVi Alvic giảm đau, hạ sốt, kháng viêm', 'description' => 'Giảm đau, kháng viêm trong các trường hợp đau cơ, khớp do chấn thương, thấp khớp, đau do viêm thần kinh như đau lưng, vẹo (sái) cổ, bong gân, căng cơ quá mức, trật khớp, đau sau giải phẫu.', 'ingredient' => 'Hoạt chất: Paracetamol 325mg, Ibuprofen 200mg.', 'intruction' => 'Trường hợp cấp tính: Uống 1 - 2 viên/lần; ngày 3 lần; hoặc theo sự chỉ dẫn của bác sĩ', 'img' => 'thuoc-giam-dau-ha-sot-khang-viem-savi-alvic.jpg', 'unit' => 'Hộp',  'brand_id' => '4', 'category_ids' => [1]],
            ['name' => 'Tydol 650 hạ sốt, giảm đau từ nhẹ đến trung bình', 'description' => 'Hạ sốt. Điều trị các cơn đau nhẹ đến trung bình gồm: Nhức đầu, đau do cảm lạnh và cảm cúm, đau họng, ', 'ingredient' => 'Hoạt chất: Acetaminophen 650mg.', 'intruction' => 'Dùng đường uống.', 'img' => 'thuoc-giam-dau-ha-sot-tydol-650mg-2.jpg', 'unit' => 'Hộp', 'brand_id' => '1', 'category_ids' => [1]],
            ['name' => 'Hỗn dịch uống Yumangel 1g trị trào ngược dạ dày, thực', 'description' => 'Thuốc có tác dụng kháng acid và cải thiện các chứng bệnh sau: loét dạ dày, loét tá tràng; viêm dạ dày; các chứng bệnh do tăng tiết acid.', 'ingredient' => 'Hoạt chất: Almagat 1.00g', 'intruction' => 'uống 1 gói hỗn dịch/ lần x 4 lần/ ngày, sau khi ăn 1 - 2 giờ và trước khi đi ngủ.', 'img' => 'yumangel-mac-dinh-2.jpg', 'unit' => 'Hộp',  'brand_id' => '1', 'category_ids' => [1]],


            ['name' => 'Dịch uống Beejuvit thanh nhiệt mát gan hỗ trợ giải độc gan', 'description' => 'Giúp thanh nhiệt, giải độc, mát gan, bảo vệ sức khỏe cho gan. Người bị nhiệt miệng, mẩn ngứa, rôm sảy, nổi mề đay do chức năng gan kém. Người có chức năng gan suy giảm hoặc sử dụng các thuốc gây độc cho gan.', 'ingredient' => 'Cao Kim ngân (Lonicera japonica thunb extract) 150 mg, Cao Diệp hạ châu (Phyllanthus amarus extract) 60 mg, Cao Thương nhĩ tử (Fructus xanthii extract) 51 mg, Cao Thổ phục linh (Rhizoma Smilacis extract) 18 mg, Cao Hạ khô thảo (Spica prunellae extract) 12 mg.', 'intruction' => 'uống 2 ống/ngày (chia 1 hoặc 2 lần).', 'img' => 'beejuvit-thanh-nhiet-mat-gan-10ml-ong-mac-dinh-2.jpg', 'unit' => 'Hộp',  'brand_id' => '1', 'category_ids' => [2]],
            ['name' => 'Bột sủi Sensa Cools hỗ trợ thanh nhiệt, bổ sung vitamin C', 'description' => 'Sản phẩm có tác dụng thanh nhiệt nhanh chóng, làm thuyên giảm các triệu chứng nhiệt như: nóng trong người, đau họng, lở miệng, nổi đẹn, khan tiếng, nổi mụn…', 'ingredient' => 'Sucrose, Axit Citric (Chất Điều Chỉnh Độ Axit) (330), Chiết Xuất Alyxia Stellate, Natri Hydro Carbonat, Chiết Xuất Quả Chanh, Vitamin C, Aspartame (Chất Tạo Ngọt) (951), Vỏ Quế, Hương Chanh Tự Nhiên, Hương Chanh Tây Tự Nhiên.', 'intruction' => '1/2 gói/lần, 2 - 3 lần/ngày.', 'img' => 'bot-sui-thanh-nhiet-sensa-cools-6-goi-mac-dinh-2.jpg', 'unit' => 'Hộp', 'brand_id' => '2', 'category_ids' => [2]],
            ['name' => 'Bright Eyes bảo vệ điểm vàng, ngừa thoái hóa mắt', 'description' => 'Bright Eyes cung cấp dưỡng chất cần thiết nuôi dưỡng mắt, giúp bảo vệ điểm vàng của mắt, ngăn ngừa thoái hóa võng mạc, làm giảm các chứng mỏi mắt.', 'ingredient' => 'Bilberry Fruit (Cao Việt Quất) 600mg, Grape Seed (Hạt nho) 75mg, Pomegranate concentrate (Chiết xuất trái lựu) 50mg, Lutein 500mcg, Zeaxanthin 500mcg.', 'intruction' => 'Uống 1 viên/lần, từ 1 - 2 lần/ngày. Uống trước hoặc sau khi ăn.', 'img' => 'bright-eyes-1-2.jpg', 'unit' => 'Chai', 'brand_id' => '3', 'category_ids' => [2]],
            ['name' => 'Cao nước Atisô Ngọc Duy không đường giúp bổ gan, lợi mật', 'description' => 'Cao nước Atisô Ngọc Duy không đường dùng tiện lợi hơn khi pha với nước hay uống trực tiếp hay uống với rượu tùy thích.', 'ingredient' => '100% cao lỏng atiso', 'intruction' => 'Uống trước hoặc sau bữa ăn. ', 'img' => 'cao-nuoc-atiso-ngoc-duy-khong-duong-giup-bo-gan-loi-mat-hop-10-ong-x-10ml-mac-dinh-2.jpg', 'unit' => 'Hộp',  'brand_id' => '3', 'category_ids' => [2]],
            ['name' => 'Dầu cá Costar Omega-3 hỗ trợ sức khỏe tim mạch, bổ mắt lọ 365 viên', 'description' => 'Sản phẩm Costar Omega 3 bổ sung EPA và DHA, hỗ trợ sức khỏe tim mạch, tốt cho mắt.', 'ingredient' => 'Thành phần khác: D-Alpha Tocopherol, Gelatin, Glycerol, nước tinh khiết.', 'intruction' => 'Uống 1 viên mỗi ngày.', 'img' => 'costar-omega-3-h-365v-mac-dinh-2.jpg', 'unit' => 'Chai', 'brand_id' => '4', 'category_ids' => [2]],
            ['name' => 'Genki Fami Nattou Ichou giúp giảm mỡ máu, phòng ngừa đột quỵ', 'description' => 'Hỗ trợ giúp giảm mỡ máu, tốt cho não, giảm nguy cơ tai biến mạch máu não do tắc mạch.', 'ingredient' => 'Dầu cá chứa DHA EPA (20% DHA và 6% EPA) 188mg, Bột chiết xuất Natto Bacillus (Chứa Nattokinase 1000FU) 50mg.', 'intruction' => 'Uống 3 viên/ngày bằng nước lọc hoặc nước ấm.', 'img' => 'genki-fami-natto-ichou-giup-giam-mo-mau-phong-ngua-dot-quy-mac-dinh-2.jpg', 'unit' => 'Chai',  'brand_id' => '2', 'category_ids' => [2]],
            ['name' => 'Siro Heviho hỗ trợ giảm ho, long đờm', 'description' => 'Hỗ trợ làm ấm họng, giải cảm, giảm ho, long đờm, tăng cường sức đề kháng cho trẻ.', 'ingredient' => 'S3-Elebosin (Chiết xuất từ Sâm đại hành, Bulbus Eleutherinis subaphyllae-tương đương lượng dược liệu 30gram)', 'intruction' => 'Trẻ từ 6 tháng tuổi đến dưới 2 tuổi: Ngày dùng 2 lần, mỗi lần 7ml.', 'img' => 'm9-chai-100ml-mac-dinh-2.jpg', 'unit' => 'Lọ',  'brand_id' => '2', 'category_ids' => [2]],
            ['name' => 'Nước giải rượu inno.N Condition hỗ trợ giải độc, bảo vệ gan', 'description' => 'Hỗ trợ giải độc gan, tăng cường chức năng gan, bảo vệ gan khỏi các tác hại của rượu bia và hóa chất độc hại.', 'ingredient' => 'Taurine 2%, chiết xuất quả hovenia dulcis (khúng khéng) 1%, bột chiết xuất nấm men 0.33%, bột chiết xuất quả cili.', 'intruction' => 'Dùng để uống trực tiếp, ngon hơn khi uống lạnh. Mỗi lần dùng 1 chai, trước hoặc sau khi uống rượu bia. Lắc nhẹ trước khi dùng.', 'img' => 'nuoc-giai-ruou-inno-n-condition-75ml-10-chai-1.jpg', 'unit' => 'Lọ', 'brand_id' => '2', 'category_ids' => [2]],
            ['name' => 'Siro Boganic Kid thanh nhiệt, giảm táo bón', 'description' => 'Hỗ trợ làm giảm các triệu chứng nóng trong như rôm sảy, mụn nhọt, phát ban, nhiệt miệng, nhiệt lưỡi.', 'ingredient' => 'Kim ngân chuông (Caulis cum folium Lonicerae): 36g.', 'intruction' => 'Trẻ từ 6 tháng đến 2 tuổi: 2,5 ml/lần, ngày 1 - 2 lần.', 'img' => 'siro-boganic-kid-100ml-1.jpg', 'unit' => 'Lọ', 'brand_id' => '2', 'category_ids' => [2]],
            ['name' => 'Nước giải rượu Rohto Alcofree hỗ trợ giải độc gan, giúp mát gan', 'description' => 'Alcofree là thực phẩm bảo vệ sức khỏe thuộc nhãn hiệu Rohto Health Science của Công ty Rohto, thương hiệu hàng đầu đến từ Nhật Bản', 'ingredient' => 'Cao đặc Đảng Sâm, Taurine', 'intruction' => 'Giảm các triệu chứng khó chịu do uống rượu bia: Uống 1 chai trước hoặc sau khi uống rượu bia.', 'img' => 'rohto-alcofree-50ml-hop-10chai-5.jpg', 'unit' => 'Chai', 'brand_id' => '1', 'category_ids' => [2]],
            ['name' => 'Dầu cá Healthy Life hỗ trợ bổ sung Omega 3, tốt cho não, mắt', 'description' => 'Hỗ trợ bổ sung Omega 3: EPA, DHA cho cơ thể. Tốt cho não, mắt và tim mạch, tăng cường sức khỏe, hỗ trợ giảm mỡ máu.', 'ingredient' => 'Dầu cá: 1000mg (chứa 300mg Acid béo Omega 3 (trong đó EPA 180mg, DHA 120mg)).', 'intruction' => 'Uống 1 viên/lần, ngày 2 lần cùng với bữa ăn.', 'img' => 'thuc-pham-bao-ve-suc-khoe-healthy-life-fish-oil-hop-100-vien-1-1.jpg', 'unit' => 'Hộp',  'brand_id' => '1', 'category_ids' => [2]],
            ['name' => 'Dầu cá Rohto V5 giúp giảm nguy cơ thoái hóa điểm vàng', 'description' => 'Với kinh nghiệm hơn 150 năm nghiên cứu và phát triển các dòng sản phẩm chăm sóc mắt, lần đầu tiên tại Việt Nam, Rohto ra mắt dòng sản phẩm chăm sóc mắt sáng khỏe và cải thiện thị lực Rohto V5 với Lutein và Zeaxanthin', 'ingredient' => 'DHA (Docosahexaenoic acid) ', 'intruction' => 'Người trưởng thành: Uống 1 viên mỗi ngày, uống với nước, không được nhai.', 'img' => 'thuc-pham-bao-ve-suc-khoe-rohto-v5-mau-moi-01.jpg', 'unit' => 'Hộp', 'brand_id' => '1', 'category_ids' => [2]],
            ['name' => 'ch Tâm Khang hỗ trợ tim mạch', 'description' => 'Một cách hiệu quả nhất để giảm suy tim, hạ mỡ máu, phá vỡ cục máu đông, mảng xơ vữa động mạch đó là tăng cường tuần hoàn mạch vành. Điều này sẽ giúp phòng ngừa và hỗ trợ điều trị làm giảm các triệu chứng của bệnh suy tim. Sản phẩm Ích Tâm Khang của thương hiệu Hồng Bàng được bào chế từ các thành phần thảo dược được tinh chế dạng cao có lợi cho tim mạch, an toàn cho sức khỏe của trái tim.', 'ingredient' => 'Cao Đan sâm 100mg (tương đương 595mg dược liệu), Cao Hoàng đằng 50mg (tương đương 450mg dược liệu), Cao Natto (từ đậu tương lên men) 50mg, L-Carnitine fumarate 20mg, Magiê (từ Magnesium lactate, Magnesium stearate, Talc) 8mg.', 'intruction' => ' Sử dụng ngày 4 viên, chia 2 lần ở những người có triệu chứng tim mạch.', 'img' => 'vien-uong-ich-tam-khang-30-vien-mac-dinh-2.jpg', 'unit' => 'Hộp',  'brand_id' => '4', 'category_ids' => [2]],
            ['name' => 'Orihiro Nattokinase Capsule 2000FU hỗ trợ tan cục máu đông, phòng ngừa đột quỵ', 'description' => 'Hỗ trợ làm tan cục máu đông, giúp giảm nguy cơ tai biến do tắc mạch.', 'ingredient' => 'Dầu đậu nành, bột Bacillus Natto chiết xuất, Sáp ong, Lecithin (từ đậu nành), bột nghệ.', 'intruction' => '', 'img' => 'vien-uong-nattokinase-2000fu-orihiro-h-60v-mac-dinh-2.jpg', 'unit' => 'Chai',  'brand_id' => '4', 'category_ids' => [2]],

            ['name' => 'Kem Ceradan Hydra duy trì độ ẩm tự nhiên cho da', 'description' => 'Kem dưỡng ẩm Ceradan Hydra (dưỡng da, dưỡng môi hyphens) giúp làn da giữ được độ ẩm cần thiết, loại bỏ những vi khuẩn có hại, loại bỏ các độc tố của vi khuẩn trên da.', 'ingredient' => 'Water, hydrogenated Polydecene, Simmondsia, Chinensis (Jojoba) Seed Oil, Butylene Glycol, Cyclopentasiloxane, Glycerin, Behenyl Alcohol, Glyceryl Stearate, Sorbitan Stearate, Beeswax, Dimethicone', 'intruction' => 'Sử dụng mỹ phẩm dưỡng da thường xuyên riêng lẻ hoặc kết hợp với Ceradan.', 'img' => 'kem-duong-am-ceradan-hydra-80g-2-1.jpg', 'unit' => 'Tuýt',  'brand_id' => '3', 'category_ids' => [3]],
            ['name' => 'Kem Eucerin Lipo Balance cân bằng độ ẩm cho da', 'description' => 'Kem dưỡng da Eucerin Lipo-Balance với thành phần Biotin và Ceramide-3 giúp phục hồi khả năng cân bằng độ ẩm của lớp lipid biểu bì.', 'ingredient' => 'Aqua, glycerin, Dicaprylyl Ether, Butyrospermum Parkii Butter (Bơ Đậu Mỡ), Hydrogenated Coco-Glycerides.', 'intruction' => 'Sử dụng vào buổi sáng và tối: Thoa đều kem dưỡng ẩm da Eucerin Lipo Balance lên mặt, cổ, ngực và nhẹ nhàng massage.', 'img' => 'kem-duong-am-eucerin-lipo-balance-50ml-1.jpg', 'unit' => 'Hộp',  'brand_id' => '3', 'category_ids' => [3]],
            ['name' => 'Kem dưỡng ban ngày LOréal Paris Revitalift dưỡng da săn chắc, giảm nếp nhăn', 'description' => 'Dưỡng da tươi trẻ ngay từ bên trong: Với hoạt chất Centella Asiatica giúp thúc đẩy quá trình tổng hợp collagen, giúp da đàn hồi, căng mịn.', 'ingredient' => 'Aqua/Water, Glycerin, Ethylhexyl Salicylate, Niacinamide, Dimethicone, Alcohol Denat., Octocrylene, Butyl Methoxydibenzoylmethane, Isopropyl Isostearate, Phenylbenzimidazole Sulfonic Acid, C13-14 Isoparaffin.', 'intruction' => 'Sử dụng hàng ngày vào mỗi buổi sáng, sau bước làm sạch da.', 'img' => 'kem-duong-ban-ngay-loreal-paris-revitalift-duong-da-san-chac-giam-nep-nhan-hop-50ml-mac-dinh-2.jpg', 'unit' => 'Hộp',  'brand_id' => '4', 'category_ids' => [3]],
            ['name' => 'Kem dưỡng La Roche-Posay Cicaplast Baume B5 phục hồi da', 'description' => 'Với công thức mới ứng dụng công nghệ hệ vi sinh vật trên da, giúp phục hồi hàng rào cấp ẩm trên bề mặt da, khôi phục da sau 1 giờ.', 'ingredient' => 'Aqua/Water/Eau, Hydrogenated Polyisobutene, Dimethicone, Glycerin, Butyrospermum Parkii Butter/Shea Butter.', 'intruction' => 'Sử dụng 2 lần/ngày lên vùng da đã được làm sạch và làm dịu với nước khoáng.', 'img' => 'kem-duong-lam-diu-mat-da-tre-em-la-roche-posay-cic-2-1.jpg', 'unit' => 'Tuýt', 'brand_id' => '4', 'category_ids' => [3]],
            ['name' => 'Kem dưỡng Obagi Retinol 1% chống lão hóa và tái tạo da', 'description' => 'Kem chống lão hóa Obagi chứa 1% Retinol thúc đẩy quá trình thay mới tế bào, đem lại kết cấu da mịn màng, giảm thiểu vẻ ngoài của nếp nhăn, rãnh sâu, cũng như cải thiện tông da không đều màu cho tổng thể da rạng rỡ, trẻ trung hơn.', 'ingredient' => 'Water (Aqua), Caprylic/Capric Triglyceride, Glyceryl Stearate, Cyclopentasiloxane, Butylene Glycol, Stearic Acid, Polysorbate 60, Butyrospermum Parkii (Shea) Butter, Glycerin, Stearyl Alcohol, Allyl Methacrylates Crosspolymer, Cyclohexasiloxane, Retinol, Polysorbate 20, Dimethicone, Simmondsia Chinensis (Jojoba) Seed Oil.', 'intruction' => 'Dùng một lượng vừa đủ cho toàn mặt, massage đều từ trong ra ngoài cho đến khi sản phẩm thấm hoàn toàn.', 'img' => 'kem-duong-obagi-retinol-1-chong-lao-hoa-tai-tao-da-tuyp-28g-1-1.jpg', 'unit' => 'Tuýt',  'brand_id' => '3', 'category_ids' => [3]],
            ['name' => 'Dầu dưỡng da ban đêm NNO Nourishing giữ ẩm, ngừa nếp nhăn', 'description' => 'Vitamin E thiên nhiên cùng với dầu Jojoba trong chế phẩm NNO Nourishing Night Oil có tác dụng dưỡng da, giữ ẩm và ngăn ngừa các vết nhăn, đốm nâu trên da, làm chậm quá trình lão hóa da, giúp làm giảm thâm quanh mắt.', 'ingredient' => 'Hydrogenated polyisobutene, Fragrance 1701, Gelatin type B 250, Glycerin, Methylparaben, Propylparaben, Nước tinh khiết.', 'intruction' => 'Bề lớp vỏ nang, đổ dầu vào lòng bàn tay sau đó bôi lên cổ và mặt, mát xa nhẹ nhàng vùng da quanh mắt và mũi trong vòng 4 phút.', 'img' => 'nno-nourishing-night-oil-hop-3vi-hinh-2.jpg', 'unit' => 'Hộp',  'brand_id' => '2', 'category_ids' => [3, 2]],
            ['name' => 'Sáp dưỡng môi Vaseline Original duy trì độ ẩm cho môi mềm mại', 'description' => 'Vaseline ra đời từ năm 1870 và được quản lý bởi tập đoàn Unilever với đa dạng các dòng sản phẩm khác nhau.', 'ingredient' => 'Octyldodecanol, Microcrystalline Wax, Caprylic/Capric Triglyceride, Ricinus Communis (Castor) Seed Oil, Cetyl Palmitate, Petrolatum.', 'intruction' => 'Vặn thỏi son lên khoảng 0.5cm (vặn cao quá sẽ dễ làm gãy son).', 'img' => 'sap-duong-moi-vaseline-original-duy-tri-do-am-cho-moi-mem-mai-mac-dinh-2.jpg', 'unit' => 'Thỏi', 'brand_id' => '2', 'category_ids' => [3]],
            ['name' => 'Sáp dưỡng môi hồng xinh Vaseline Rosy Lips duy trì độ ẩm cho môi', 'description' => 'Vaseline ra đời từ năm 1870 và được quản lý bởi tập đoàn Unilever với đa dạng các dòng sản phẩm khác nhau', 'ingredient' => 'Octyldodecanol, Microcrystalline Wax, Caprylic/Capric Triglyceride, Ricinus Communis (Castor) Seed Oil, Cetyl Palmitate.', 'intruction' => 'Vặn thỏi son lên khoảng 0.5cm (vặn cao quá sẽ dễ làm gãy son).', 'img' => 'sap-duong-moi-vaseline-rosy-lips-mac-dinh-2.jpg', 'unit' => 'Thỏi',  'brand_id' => '2', 'category_ids' => [3]],
            ['name' => 'Serum Balance Hyaluronic cấp nước, hạn chế tiết dầu', 'description' => 'Serum Balance Hyaluronic tăng gấp 5 lần khóa ẩm cho làn da nhờ thành phần chứa 5% Hyasol PF, một loại HA đặc biệ', 'ingredient' => 'Aqua (Water), Glycerin, Carrageenan, Panthenol, Phenoxyethanol, Ethylhexylglycerin, Disodium Edta, Sodium Hyaluronate.', 'intruction' => 'Vào mỗi sáng và tối, thoa serum lên vùng mặt và vùng có, massage nhẹ nhàng.', 'img' => 'serum-balance-hyaluronic-duong-am-30ml-1.jpg', 'unit' => 'Chai', 'brand_id' => '2', 'category_ids' => [3]],
            ['name' => 'Son dưỡng Cocoon dầu dừa Bến Tre bảo vệ, chống khô môi', 'description' => 'Son dưỡng có mùi thơm tự nhiên từ dầu dừa Bến Tre giúp dưỡng ẩm, bảo vệ và chống khô môi do thời tiết.', 'ingredient' => 'Cocos Nucifera Oil, Bis-Diglyceryl Polyacyladipate-2, Synthetic Beeswax, C10-18 Triglycerides, C15-19 Alkane, Butyrospermum Parkii Butter, Candelilla Cera, Tocopheryl Acetate.', 'intruction' => 'Thoa sản phẩm trực tiếp lên môi, có thể dùng như một lớp lót trước khi thoa son màu để tránh gây khô môi.', 'img' => 'son-duong-dau-dua-ben-tre-cocoon-5g-1.jpg', 'unit' => 'Thỏi',  'brand_id' => '3', 'category_ids' => [3]],
            ['name' => 'Son dưỡng môi LipIce không màu chuyển kem mịn hương dâu', 'description' => 'LipIce là thương hiệu dưỡng môi hồng Nhật Bản được thành lập từ năm 1899, thuộc dòng sản phẩm chăm sóc môi của Rohto – tập đoàn chuyên nghiên cứu, phát triển, sản xuất các sản phẩm dược mỹ phẩm.', 'ingredient' => 'Paraffinum Liquidum, Butyrospermum Parkii (Shea) Butter, Microcrystalline Wax, Squalane, Synthetic Wax, Ethylhexyl Methoxycinnamate.', 'intruction' => 'Thoa tực tiếp lên môi.', 'img' => 'son-duong-moi-lipice-khong-mau-chuyen-kem-min-huong-dau-1.jpg', 'unit' => 'Thỏi', 'brand_id' => '3', 'category_ids' => [3]],
            ['name' => 'Sữa chống nắng Sunplay Skin Aqua Clear White SPF 50+/PA++++', 'description' => 'Sữa chống nắng Sunplay Skin Aqua Clear White SPF 50/PA++++ 25g với công thức cải tiến, không chứa cồn, không gây khô da, dịu nhẹ với da nhạy cảm, tạo màng chống nắng hiệu quả và cấp ẩm cho da. Chỉ số chống nắng cao, bảo vệ da dưới tác hại của ánh sáng mặt trời trong suốt nhiều giờ.', 'ingredient' => 'Water, Cyclopentasiloxane, Zinc Oxide, Ethylhexyl Methoxycinnamate, Methyl Methacrylate Crosspolymer, Dimethicone, PEG-9 Polydimethylsiloxyethyl Dimethicone, Simmondsia Chinensis (Jojoba) Seed Oil.', 'intruction' => 'Lắc kỹ trước khi sử dụng.', 'img' => 'sua-chong-nang-sunplay-skin-aqua-clear-white-25g-1-1.jpg', 'unit' => 'Chai',  'brand_id' => '3', 'category_ids' => [3]],
            ['name' => 'Sữa chống nắng Sunplay Skin Aqua Tone Up UV SPF50+/PA++++ hiệu chỉnh sắc da', 'description' => 'Sữa chống nắng Sunplay Skin Aqua Tone Up UV SPF50+/PA++++ chai 50g là sản phẩm thuộc tập đoàn Rohto-Mentholatum, một tập đoàn hàng đầu trong lĩnh vực sản xuất dược phẩm và mỹ phẩm.', 'ingredient' => 'Hyaluronic Acid, Vitamin C, Vitamin B3, Pearl Powder, Cyclopentasiloxane, Water, Zinc Oxide, Ethylhexyl Methoxycinnamate, Methyl Methacrylate Crosspolymer, Isononyl Isononanoate, Talc, Lauryl PEG-9 Polydimethylsiloxyethyl Dimethicone, Silica, Dimethicone, Polymethylsilsesquioxane, Niacinamide.', 'intruction' => 'Lắc kỹ trước khi dùng.', 'img' => 'sua-chong-nang-sunplay-skin-aqua-spf-50-pa-50g-1.jpg', 'unit' => 'Chai', 'brand_id' => '1', 'category_ids' => [3]],
            ['name' => 'Serum Garnier Light Complete Vitamin C tăng cường trắng da, mờ thâm', 'description' => 'Serum Garnier Light Complete Vitamin C chứa gấp 30 lần vitamin C so với sản phẩm thông thường cùng với chiết xuất quả yuzu, giúp da trắng sáng bật tone, mờ thâm nám.', 'ingredient' => 'Thành phần chính: Hexylene Glycol, Disodium Cocoamphodiacetate, Ascorbyl Glucoside (Vitamin C).', 'intruction' => 'Sử dụng serum dưỡng trắng da hàng ngày vào buổi sáng và tối ở mặt và cổ, sau bước làm sạch da.', 'img' => 'tinh-chat-garnier-duong-trang-sang-da-min-mo-tham-30ml-mac-dinh-2-1.jpg', 'unit' => 'Chai', 'brand_id' => '1', 'category_ids' => [3]],

            ['name' => 'Băng cá nhân vải Urgo Durable', 'description' => 'Trong tủ thuốc gia đình của mỗi nhà cần nên có các loại thiết bị, dụng cụ y tế cần thiết như nhiệt kế, máy đo huyết áp, máy đo đường huyết, bông gòn, băng gạc, băng cá nhân,... để có thể sử dụng ngay khi cần dùng đến.', 'ingredient' => 'Gạc màu trắng, phủ lớp lưới polyethylene không dính vào vết thương, không gây đau khi thay băng.', 'intruction' => 'Vệ sinh, sát khuẩn, rửa sạch và lau khô nhẹ nhàng vết thương và khu vực xung quanh vết thương.', 'img' => 'bang-ca-nhan-do-dinh-cao-urgo-durable-hop-20-mieng-mac-dinh-2.jpg', 'unit' => 'Hộp', 'brand_id' => '4', 'category_ids' => [4]],
            ['name' => 'Nhiệt kế điện tử đo thân nhiệt Omron', 'description' => 'Thương hiệu Omron - chuyên cung cấp các sản phẩm chăm sóc sức khỏe như: Máy đo huyết áp, máy xông khí dung, nhiệt kế điện tử, máy xung điện trị liệu,... sử dụng trong bệnh viện, cũng như trong gia đình, được mọi người tin dùng nhiều hiện nay. ', 'ingredient' => 'Nguồn điện: 1,5VDC, 1 pin LR41.Công suất điện: 0,1 mW. Tuổi thọ của pin khoảng: 2 năm hoặc hơn (nếu sử dụng 3 lần mỗi ngày).', 'intruction' => 'Nếu có thể, nên dùng vỏ bọc đầu đo mỗi lần đo. Thay vỏ bọc mới sau mỗi lần sử dụng.', 'img' => 'do-nhiet-do-1-1.jpg', 'unit' => '',  'brand_id' => '2', 'category_ids' => [4]],
            ['name' => 'Gạc y tế Bảo Thạch túi 10 miếng', 'description' => 'Ngày nay trong tủ thuốc gia đình của mỗi nhà cần nên có các loại thiết bị, dụng cụ y tế cần thiết như nhiệt kế, máy đo huyết áp, máy đo đường huyết, bông gòn, băng gạc, băng cá nhân,... để có thể sử dụng ngay khi cần dùng đến.', 'ingredient' => '100% sợi cotton.', 'intruction' => 'Xé bao bì theo đường cắt sẵn. Dùng băng gạc y tế thấm thuốc sát trùng để lau rửa vết thương hoặc đắp lên vết thương cần chăm sóc.', 'img' => 'gac-bao-thach-5x6x12-hinh-2.jpg', 'unit' => 'Túi', 'brand_id' => '2', 'category_ids' => [4]],
            ['name' => 'Găng tay y tế có bột Latex Im Glove size M', 'description' => 'Dùng trong thực phẩm, công nghiệp, y tế và các mục đích thông thường khác.', 'ingredient' => 'Cao su tự nhiên.', 'intruction' => '', 'img' => 'gang-tay-y-te-co-bot-latex-im-glove-size-m-hop-50-doi-1.jpg', 'unit' => 'Hộp',  'brand_id' => '2', 'category_ids' => [4]],
            ['name' => 'Khăn hạ sốt Dr.Papie 0+ cho bé', 'description' => 'Khăn lau chườm giúp hạ nhiệt, giảm sốt trong trường hợp trẻ bị sốt chưa cần dùng đến thuốc hạ sốt. ', 'ingredient' => 'Nước tinh khiết, Xanthan gôm, Glycerin, Lô hội, Dịch chiết Cỏ nhọ nồi, tinh dầu tía tô, tinh chất chanh, Sodium benzoate, Chlorophyll (diệp lục từ tảo), vitamin E. ', 'intruction' => 'Đắp khăn đã tẩm sẵn dịch ở các vị trí có mạch máu lớn đi qua: 2 nách, 2 bên cổ, 2 bên bẹn, trán, gan bàn chân, bàn tay. ', 'img' => 'khan-ha-sot-drpapie-0-h-5-goi-mac-dinh-2.jpg', 'unit' => 'Hộp',  'brand_id' => '2', 'category_ids' => [4]],
            ['name' => 'Khẩu trang y tế Bísou 3D Mask màu trắng size M', 'description' => 'Khẩu trang y tế Bísou 3D Mask có thiết kế 3D thông minh, ôm sát khuôn mặt.', 'ingredient' => '100% vải không dệt polypropylene', 'intruction' => 'Mở mặt trong khẩu trang. Đeo dây vào tai.', 'img' => 'khau-trang-y-te-bisou-3d-mask-mau-trang-size-m-1.jpg', 'unit' => 'Túi',  'brand_id' => '1', 'category_ids' => [4]],
            ['name' => 'Khẩu trang y tế Winer 4 lớp màu trắng', 'description' => 'Lọc sạch khí ngăn ngừa vi khuẩn, không gây kích ứng. Ngăn bụi, khí độc, mùi hôi, ô nhiễm. Ngăn ngừa các bệnh lây qua đường hô hấp. Không sợi thủy tinh, không gây dị ứng.', 'ingredient' => '3 lớp vải không dệt.', 'intruction' => 'Đặt khẩu trang lên mặt đeo dây vòng qua tai hướng mặt có màu ra phía ngoài.', 'img' => 'khau-trang-y-te-winer-4-lop-mau-trang-hop-50-cai-1.jpg', 'unit' => 'Hộp', 'brand_id' => '1', 'category_ids' => [4]],
            ['name' => 'Máy đo nồng độ oxy trong máu', 'description' => 'Máy đo nồng độ oxy trong máu SpO2 Jumper JPD-500D là một thiết bị, dụng cụ y tế điện tử được sử dụng để đo mức độ oxy hóa của máu trong cơ thể. Máy đo này thuộc loại máy đo không xâm lấn, không đau và không gây bất cứ khó chịu nào cho bệnh nhân.', 'ingredient' => '1 máy Jpd 500D Led.', 'intruction' => 'Cho ngón tay vào khe giữa 2 thân máy, phần móng tay quay lên trên phía màn hình, bấm nút nguồn thiết bị sẽ bắt đầu tiến hành phép đo.', 'img' => 'may-do-nong-do-oxy-mau-spo2-jumper-jpd-500d-led-1.jpg', 'unit' => '', 'brand_id' => '1', 'category_ids' => [4]],
            ['name' => 'Miếng dán Tika-Patch giảm đau cơ, xương khớp', 'description' => 'Miếng dán Tika-Patch hỗ trợ giảm đau trong cách trường hợp bong gân, đau vai, đau cơ, đau lưng,...', 'ingredient' => 'Menthol, long não, eucalyptol, tinh chất ớt, menthyl salicylate, hot melt adhesive, lanolin, dầu farafin, zinc oxide, tinh dầu thơm.', 'intruction' => 'Làm sạch và khô vùng da cần dán, gỡ miếng film ra khỏi miếng dán, dán mặt dính lên vùng da sạch và khô nơi muốn dán như: lưng, vai, cơ bắp,...', 'img' => 'mieng-dan-con-ho-tika-patch-tiger-plaster-4-mieng-002.jpg', 'unit' => 'Miếng',  'brand_id' => '1', 'category_ids' => [4]],
            ['name' => 'Miếng dán hạ sốt Lion Hiepita For Baby giảm cơn sốt cho bé', 'description' => 'Cung cấp giải pháp làm mát, giúp giảm sốt khó chịu bằng cách tận dụng sự hấp thụ nhiệt.', 'ingredient' => 'Tinh dầu Hương thảo, Tinh dầu Cây xô thơm, Tinh dầu Húng tây, Tinh dầu Bạc Hà, Tinh dầu Khuynh Diệp, Tinh dầu Hoa Oải Hương, Nước,...', 'intruction' => 'Giữ cho vùng da khô ráo và sử dụng miếng dán ngay sau khi mở gói. Gỡ bỏ miếng dán phim và dán lên vùng da cần làm mát (trán). Thay miếng dán mới sau mỗi 8 giờ sử dụng.', 'img' => 'mieng-dan-ha-sot-lion-hiepita-for-child-giam-con-sot-cho-be-0-1.jpg', 'unit' => 'Hộp', 'brand_id' => '4', 'category_ids' => [4]],
            ['name' => 'Miếng dán hạ sốt ByeBye Fever trẻ sơ sinh', 'description' => 'Miếng dán hạ sốt ByeBye Fever trẻ sơ sinh đến từ thương hiệu Hisamitsu (Nhật Bản), sản phẩm có vị đắng để tránh nuốt phải.', 'ingredient' => 'Glycerin, nước, polymer', 'intruction' => 'Gỡ bỏ miếng phim và dán mặt dính trực tiếp lên da. Đặt miếng dán vào tủ lạnh trước khi sử dụng để trăng hiệu quả làm mát', 'img' => 'mieng-dan-ha-nhiet-lam-lanh-nhanh-byebye-fever-sup-2.jpg', 'unit' => 'Hộp',  'brand_id' => '3', 'category_ids' => [4]],
            ['name' => 'Nhiệt kế điện tử đo thân nhiệt Microlife MT 550', 'description' => 'Nhiệt kế điện tử đo thân nhiệt Microlife MT 550 là giải pháp thay thế nhiệt kế Thủy ngân, cảm ứng nhiệt bằng công nghệ đầu dò vàng GoldTerm không gây dị ứng và cho kết quả nhanh chỉ trong 10 giây, nhanh gấp 6 lần nhiệt kế điện tử thông thường.', 'ingredient' => 'Màn hình đèn Led', 'intruction' => '', 'img' => 'nhiet-ke-but-dien-tu-microlife-mt-550-2-1.jpg', 'unit' => '', 'brand_id' => '3', 'category_ids' => [4]],
            ['name' => 'Túi chườm đa năng Mặt Trời TTV', 'description' => 'Túi chườm đa năng Mặt Trời TTV là sản phẩm đạt tiêu chuẩn chất lượng Châu Âu.', 'ingredient' => 'Túi chườm đa năng Mặt Trời TTV, Một dây sạc điện, Một sách hướng dẫn bảo hành, hộp đựng.', 'intruction' => 'Vị trí chườm: cổ, nách, bẹn, lưng, bụng, bàn tay, bàn chân, hoặc trên vùng lạnh vùng đau cụ thể. Để có cách điều trị hiệu quả nhất, hãy hỏi ý kiến bác sĩ hoặc điều dưỡng viên.', 'img' => 'tui-chuom-da-nang-ttv-2-1.jpg', 'unit' => '',  'brand_id' => '3', 'category_ids' => [4]],
            ['name' => 'Túi chườm nóng lạnh Greetmed', 'description' => 'Túi chườm lạnh là sản phẩm lí tưởng cho những ngày đông giá rét, không chỉ có khả năng sưởi ấm mà còn có thể chườm lạnh để giảm sốt hiệu quả.', 'ingredient' => 'Cao su thiên nhiên dẻo mềm.', 'intruction' => 'Chườm lạnh: Cho nước vào túi chườm và để trong ngăn mát tủ lạnh thời gian từ 30, 45 phút trước khi sử dụng.', 'img' => 'tui-chuom-nong-greetmed-mac-dinh-2.jpg', 'unit' => '', 'brand_id' => '3', 'category_ids' => [4]],

            ['name' => 'Kem Bepanthen Balm ngừa hăm tã, kích ứng da cho bé', 'description' => 'Kem Bepanthen Balm là một sản phẩm được thiết kế để ngăn ngừa và điều trị hăm tã, kích ứng da do da của bé bị ướt, nhờn hoặc cọ sát liên tục. Đây là một sản phẩm chất lượng được nhiều bà mẹ tin dùng và đánh giá cao.', 'ingredient' => 'Aqua; lanolin; paraffinum liquidum; petrolatum; panthenol; prunus amygdalus dulcis oil; cera alba; cetyl alcohol; stearyl alcohol; ozokerite; glyceryl oleate, lanolin alcohol.', 'intruction' => 'Da bị tổn thương: Xoa Bepanthen® Balm mỗi ngày một hoặc nhiều lần nếu cần thiết.', 'img' => 'bepanthen-balm-30g-mac-dinh-3.jpg', 'unit' => 'Tuýt',  'brand_id' => '3', 'category_ids' => [5, 3]],
            ['name' => 'Dầu Johnsons Baby massage và dưỡng ẩm cho bé', 'description' => 'Johnsons Baby có hàng loạt các sản phẩm chăm sóc trẻ em bao gồm sản phẩm tắm gội, kem dưỡng, bỉm tã, dầu massage dưỡng ẩm,...Với các thành phần được nghiên cứu kỹ lưỡng để đảm bảo an toàn và hiệu quả cho bé.', 'ingredient' => 'Dầu khoáng và Fragrance', 'intruction' => 'Xoa bóp nhẹ nhàng trên da trước khi tắm hoặc ngay sau khi tắm để giữ ẩm cho bé.', 'img' => 'dau-massage-va-duong-am-johnson-50ml-bhx-mac-dinh-2.jpg', 'unit' => 'Chai', 'brand_id' => '3', 'category_ids' => [5]],
            ['name' => 'Kem bôi da trẻ em Ích Nhi dịu vết ngứa, hăm tã, côn trùng đốt', 'description' => 'Chống hăm tã là một vấn đề được quan tâm nhiều trong việc chăm sóc trẻ em của các mẹ ngày nay. Việc sử dụng các sản phẩm kem chống hăm cho bé, phấn hoặc sáp chống hăm là cách hiệu quả để giữ cho vùng da dưới đồ của bé luôn khô ráo, sạch sẽ và giúp da trẻ không chà sát với bề mặt tã lót.', 'ingredient' => 'Chiết xuất Cúc la mã (Matricaria chamomilla extract), Chiết xuất Rau má (Centella asiatica extract), Kẽm oxyd (Zinc oxide), D-panthenol, Vitamin E (DL-alpha-Tocopheryl acetat), Allantoin (5-ureidohydantoin), Glycerin.', 'intruction' => 'Làm sạch vùng da bị tổn thương.', 'img' => 'kem-boi-da-tre-em-ich-nhi-20g-1.jpg', 'unit' => 'Tuýt', 'brand_id' => '2', 'category_ids' => [5]],
            ['name' => 'Kem bôi dịu da Dizizone Baby làm dịu vết mẫn ngứa, hăm da cho bé', 'description' => 'Các sản phẩm chống hăm tã luôn được quan tâm trong việc chăm sóc trẻ em của các mẹ ngày nay. Việc sử dụng kem chống hăm cho bé tã là cách hiệu quả để giữ cho vùng da dưới đồ tã của bé sạch khô, khô ráo và không chà sát với bề mặt tã lót, giúp làm dịu, dưỡng ẩm làn da nhạy cảm của trẻ.', 'ingredient' => 'Purified Water, Glyceryl Stearate SE, Coco-Caprylate/Caprate, Zinc Oxide (kẽm oxit), Butyrospermum Parkii (Shea) Butter, Glycerin, Ceteareth-25, Oryza Sativa (Rice) Germ Oil, Dimethicone, Nano Silver (Nano Bạc).', 'intruction' => 'Làm sạch, thấm khô và thoa một lượng vừa đủ kem Dizigone Baby lên vùng da cần chăm sóc. Sử dụng ngày 3 - 4 lần hoặc nhiều hơn.', 'img' => 'kem-boi-diu-da-cho-be-dizigone-baby-30g-mac-dinh-2.jpg', 'unit' => 'Tuýt', 'brand_id' => '2', 'category_ids' => [5, 3]],
            ['name' => 'Kem dưỡng ẩm Kutieskin Moisturzing làm dịu, giảm khô ngứa, nứt nẻ', 'description' => 'Dưỡng ẩm Kutieskin Moisturzing làm mềm da, giúp da bé luôn mềm mại và chống hăm, giảm tình trạng khô ngứa, nứt nẻ da.', 'ingredient' => 'Purified water, Butyrospermum Parkii Butter, Vaseline, Glycerin, C15-19 Alkane, Xylitylglucoside (and) Anhydroxylitol (and) Xylitol.', 'intruction' => 'Vệ sinh da sạch sẽ.', 'img' => 'kem-duong-am-kutieskin-moisturizing-cream-30g-1.jpg', 'unit' => 'Tuýt', 'brand_id' => '3', 'category_ids' => [5, 3]],
            ['name' => 'Nước hoa Johnsons Morning Dew hương nắng mai nhẹ nhàng', 'description' => 'Nước hoa cho bé Johnsons Morning Dew sở hữu mùi hương nắng mai nhẹ nhàng và dịu nhẹ.', 'ingredient' => 'Alcohol Denat, Water, Fragramce, PEG-40, Hydrogenated Castor Oil, Sodium Citrate, Citric Acid, Sodium Hydroxide.', 'intruction' => 'Nhẹ nhàng thoa cho bé.', 'img' => 'nuoc-hoa-johnsons-huong-nang-mai-125ml-1-1.jpg', 'unit' => 'Chai', 'brand_id' => '3', 'category_ids' => [5]],
            ['name' => 'Nước tắm gội thảo dược Dr.Papie ngừa rôm sảy, mẩn ngứa cho bé', 'description' => 'Chiết xuất lá Trà Shan Tuyết có tác dụng thanh nhiệt, làm mát giúp chống rôm sảy, mẩn ngứa.', 'ingredient' => 'Dịch chiết lá Trà Shan Tuyết (Camellia Sinensis Leaf Extract)', 'intruction' => 'Lượng nước tắm sử dụng phụ thuộc vào mỗi trẻ.', 'img' => 'nuoc-tam-goi-thao-duoc-dr-papie-cho-be-0.jpg', 'unit' => 'Chai', 'brand_id' => '1', 'category_ids' => [5]],
            ['name' => 'Phấn rôm cho bé Pigeon Prickly Heat bảo vệ làn da bé khỏi ngứa và mẩn đỏ', 'description' => 'Pigeon là sản phẩm của Công ty Pigeon Honyuki Honpo, được thành lập năm 1957 tại Nhật Bản, là thương hiệu chăm sóc cho bé nổi tiếng với nhiều sản phẩm chất lượng như bình sữa, núm vú, đồ dùng cho bé, nước giặt, sữa tắm, dầu gội, phấn thơm,...', 'ingredient' => 'Talc, Calamine, Zinc Oxide, Fragrance, Simmondsia Chinensis (Jojoba) Seed Oil, Bisabolol.', 'intruction' => 'Cho phấn vào lòng bàn tay, thoa đều lên cổ, nách, ngực, lưng hoặc bất kỳ vùng da nào của bé có các triệu chứng mẩn đỏ do rôm sảy.', 'img' => 'phan-rom-cho-be-pigeon-prickly-heat-100g-1-3.jpg', 'unit' => 'Chai', 'brand_id' => '1', 'category_ids' => [5]],
            ['name' => 'Sữa tắm gội Babycoccole chiết xuất hoa sen ngừa rôm sảy giữ ẩm cho da', 'description' => 'Tắm gội dịu nhẹ dành riêng cho da tóc của trẻ sơ sinh trong suốt thời gian đầu vừa ra đời.', 'ingredient' => 'Betaglucans (yến mạch) và bisabolol (hoa cúc), chiết xuất hoa sen.', 'intruction' => 'Rót lượng nhỏ vào lòng bàn tay, nhẹ nhàng thoa lên tóc và da của bé, xả sạch bằng nước ấm với nhiệt độ không vượt quá nhiệt độ cơ thể của bé (khoảng 36.5°C).', 'img' => 'sua-tam-goi-babycoccole-chiet-xuat-hoa-sen-ngua-rom-say-giu-am-cho-da-mac-dinh-2.jpg', 'unit' => 'Chai', 'brand_id' => '1', 'category_ids' => [5]],
            ['name' => 'Sữa tắm gội cho bé Cetaphil Baby Gentle hương dịu nhẹ', 'description' => 'Sữa tắm gội dịu lành Cetaphil Baby Gentle Wash & Shampoo với các thành phần từ thiên nhiên giúp chăm sóc và làm sạch làn da mỏng manh của trẻ sơ sinh, đồng thời bảo vệ và cung cấp độ ẩm cho sự phát triển khỏe mạnh của da bé.', 'ingredient' => 'Aqua, Cocamidopropyl Betaine, Disodium Cocoamphodiacetate, Glycerin, Coco-Glucoside, Acrylates/C10-30 Alkyl Acrylate Crosspolymer, Citric Acid, Heliotropine, Panthenol, Parfum, Phenoxyethanol.', 'intruction' => 'Đổ ra tay hoặc bông tắm và xoa nhẹ lên da và tóc.', 'img' => 'sua-tam-goi-cho-be-cetaphil-baby-gentle-huong-diu-nhe-400ml-1-1.jpg', 'unit' => 'Chai', 'brand_id' => '4', 'category_ids' => [5]],
            ['name' => 'Sữa tắm gội trẻ em Baby Shark dịu nhẹ, ngừa rôm sảy', 'description' => 'Dầu gội, sữa tắm cho bé giúp làm sạch da và tóc, khử mùi hôi, làm dịu da khi bị: rôm sảy, mụn nhọt, mẩn ngứa, viêm da, hăm da,... cho da bé mềm mại, sáng sạch hơn.', 'ingredient' => 'Water, Cocamidopropyl Betaine, Disodium Laureth Sulfosuccinate, Glycerine, Sodium Cocoamphoacetate.', 'intruction' => 'Lấy một lượng sữa tắm gội trẻ em Baby Shark vừa đủ ra tay rồi thoa lên tóc và toàn thân để tạo bọt. Massage một cách nhẹ nhàng sau đó tắm gội lại cho bé bằng nước sạch.', 'img' => 'sua-tam-goi-tre-em-baby-shark-350ml-1.jpg', 'unit' => 'Chai', 'brand_id' => '4', 'category_ids' => [5]],
            ['name' => 'Tắm gội toàn thân cho bé Johnsons Baby mềm mại như bông', 'description' => 'Dầu gội, sữa tắm cho bé Johnson & Johnson từ lâu đã là thương hiệu sản phẩm cho trẻ em cực kỳ an toàn, dịu nhẹ và phù hợp với làn da của bé. ', 'ingredient' => 'Water, Cocamidopropyl Betaine, PEG-80 Sorbitan Laurate, Decyl Glucoside, Acrylates/C10-30 Alkyl Acrylate Crosspolymer, Phenoxyethanol, Sodium Benzoate, Fragrance,...', 'intruction' => 'Để nơi khô mát, tránh ánh sáng, Đậy nắp kỹ sau khi sử dụng.', 'img' => 'tam-goi-cho-be-johnsons-mem-min-nhu-bong-200ml-1.jpg', 'unit' => 'Chai', 'brand_id' => '4', 'category_ids' => [5]],
            ['name' => 'Tắm gội toàn thân Pigeon Hoa Hướng Dương cấp ẩm cho da bé', 'description' => 'Hình thành màng dưỡng ẩm cho da sau bước làm sạch với nước, thấy được sự mượt mà trơn tru của làn da ngay sau khi sử dụng với nước. Các sản phẩm chuyên dụng cho làn da của trẻ luôn cần có lớp màng cấp ẩm này để nuôi dưỡng và bảo vệ làn da của bé.', 'ingredient' => 'Purified Water, Cocamidopropyl Betaine, Sodium Myreth Sulfate, Sodium Cocoamphoacetate, Glycerin, Fragrance, PEG-250 Distearate, Phenoxyethanol, Polyquaternium-10, Citric Acid, Sodium Benzoate, Hydroxyacetophenone.', 'intruction' => 'Cho một lượng sữa tắm gội Pigeon vào bông tắm hoặc lòng bàn tay, nhẹ nhàng thoa đều lên da và tóc bé.', 'img' => 'tam-goi-toan-than-2-trong-1-khong-paraben-pigeon-mac-dinh-2.jpg', 'unit' => 'Chai', 'brand_id' => '1', 'category_ids' => [5]],
            ['name' => 'Tắm gội toàn thân Johnsons Baby top to toe dịu nhẹ cho bé', 'description' => 'Johnsons Baby Top to Toe đến từ dòng dầu gội, sữa tắm cho bé johnson & johnson với công thức dịu nhẹ giúp giữ cho da và tóc của bé mềm mượt và sạch sẽ sau mỗi lần sử dụng.', 'ingredient' => ' Glycerin, axit Citric, Sodium Benzoate, PEG-80 Sorbitan Laurate...', 'intruction' => 'Làm ướt da bé, thoa đều lên tóc và cơ thể bé hoặc hòa vào thau tắm cho bé tắm, sau đó làm sạch với nước ấm.', 'img' => 'tam-goi-toan-than-j-j-200ml-1-1.jpg', 'unit' => 'Chai', 'brand_id' => '1', 'category_ids' => [5]],



        ];

        foreach ($items as $item) {
            $randomNumber = mt_rand(0, 9999999);
            $item['code'] = str_pad($randomNumber, 7, '0', STR_PAD_LEFT);
            $categoryIds = $item['category_ids'];
            unset($item['category_ids']);
            $product = Product::updateOrCreate(['code' => $item['code']], $item);
            $product->assignCategory($categoryIds);
        }
    }
}
